### PR TITLE
adding bluesky as library

### PR DESCRIPTION
**Pull request by FadingFire**
trying to make a standalone console that can run bluesky commands in bluesky

### CODE REVIEW

**Review by Wazeback — COMMENTED** [review]
maybe its me but is the start.py in the blue_sky folder or outside of it

**Comment by FadingFire** [comment]
its outside of it, i deleted the bluesky folder because we dont need te plugin anymore

**Comment by Wazeback** [comment]
it might be useful to add back a blue sky controller folder that handles all of the direct bluesky imports etc. That way you can easily import functions instead of having to import a start.py that is just in the main folder

**Comment by FadingFire** [comment]
aight
did that

**Pull request closed without merging**
