### PR TITLE
Getting the root of the server to run better

### PR DESCRIPTION
**Pull request by Wazeback**
Testing only in code not a live env. 
!!! CHECK IN LIVE ENV !!!

### CODE REVIEW

**Comment by Wazeback** [comment]
Just test if everything works if u use this, I dont have an env to test this in and I pray to god that I wrote my stuff well. If there are any errors etc, comment them for me to debug and fix them later.

**Comment by Wazeback** [comment]
I'm going to see if I can get a guy from my work to look at what the ever living fuck is wrong with the code. Can you send me some screenshots, of what's happening in your browser so i don't have to open Discord in a meeting...

**Comment by FadingFire** [comment]
image1
image

**Comment by Wazeback** [comment]
This is due to stupid stuff the reason we switch over to flask

**Pull request closed without merging**
